# Generated by Django 5.2.6 on 2025-09-29 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conference', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_away', models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('N', 'Neutral')], default='H', max_length=1)),
                ('oklahoma_score', models.PositiveIntegerField()),
                ('opponent_score', models.PositiveIntegerField()),
                ('result', models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Loss')], max_length=1)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('season_record', models.CharField(blank=True, max_length=20)),
                ('conference_record', models.CharField(blank=True, max_length=20)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
