# Generated by Django 5.2.6 on 2025-10-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
