# Generated by Django 5.2.6 on 2025-10-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_game_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
