# Generated by Django 5.2.6 on 2025-10-16 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='stats.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='cfbd_game_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='conference_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='home_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='stats.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='neutral_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='alternate_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='cfbd_team_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='oklahoma_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
