# Generated by Django 5.2.7 on 2025-10-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_add_game_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='unique_game_date_home_away',
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('date', 'home_team', 'away_team')},
        ),
    ]
