# Generated by Django 5.2.6 on 2025-11-05 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_remove_game_unique_game_date_home_away_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='home_away',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('A', 'Away'), ('N', 'Neutral')], max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.team'),
        ),
    ]
